# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end

  config.vm.define :servidorJupyterUbuntu do |servidorJupyterUbuntu|
    servidorJupyterUbuntu.vm.box = "bento/ubuntu-22.04"
    servidorJupyterUbuntu.vm.network :private_network, ip: "192.168.100.4"
    servidorJupyterUbuntu.vm.hostname = "servidorJupyterUbuntu"
    servidorJupyterUbuntu.vm.provision "shell", path: "install_jupyter.sh"
  end
end
