version: '3.7'
services:
  vsftpd:
    image: panubo/vsftpd # fauria/vsftpd
    environment:
      - FTP_USER=user
      - FTP_PASSWORD=password
    volumes:
      - ./files:/srv
    expose:
      - "21"
    network_mode: "host"
