# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end

  config.vm.define :kubernetesServer do |kubernetesServer|
    kubernetesServer.vm.box = "bento/ubuntu-22.04"
    kubernetesServer.vm.network :private_network, ip: "192.168.100.10"
    kubernetesServer.vm.hostname = "kubernetesServer"
    kubernetesServer.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 3072
    end
    # kubernetesServer.disksize.size = "40GB"
    kubernetesServer.vm.provision "shell", path: "script.sh"
  end
end